server:
  port: 8089
  servlet:
    context-path: '/Demo'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
info:
  application:
    name: Demo-Application
    description: An Application to Demo Deploy
    author: Akash Singh
    version: '@project.version@'
spring:
  profiles:
    active: prod